spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/herokutest
    username: postgres
    password: postgres
  security:
    user:
      name: admin
      password: admin